### ISSUE TITLE
CMakeLists.txt中lib及h文件安装目录设定有误

### ISSUE THREAD

**Issue by xatabhk** [uavs3/uavs3e#13]
原因是使用了固定目录, 即/usr/include/与/usr/lib:
install(TARGETS uavs3e LIBRARY DESTINATION /usr/lib ARCHIVE DESTINATION /usr/lib)
install(FILES ../inc/uavs3e.h DESTINATION /usr/include/uavs3e/)
install(FILES ../inc/com_api.h DESTINATION /usr/include/uavs3e/)

而应为:
install(TARGETS uavs3e LIBRARY DESTINATION ${CMAKE_INSTALL_LIB_DIR} ARCHIVE DESTINATION ${CMAKE_INSTALL_LIB_DIR})
install(FILES ../inc/uavs3e.h DESTINATION ${INSTALL_INCLUDE_DIR}/uavs3e/)
install(FILES ../inc/com_api.h DESTINATION ${INSTALL_INCLUDE_DIR}/uavs3e/)

若CMAKE_INSTALL_PREFIX为空, 才设为缺省值/usr.

**Comment by zywang-sirius** [comment]
非常感谢，已经修改
