### ISSUE TITLE
[仓库分支]添加仓库分支说明

### ISSUE THREAD

**Issue by Yang-Xijie** [uavs3/uavs3e#27]
目前版本库中共有master, Realtime, aq, cudetheqt, sobel_ql五个分支

在任何README.md中都没有关于这几个分支差异的说明，希望能在主分支的README中添加关于分支的说明

如果分支与master分支相差较大，希望能在该分支下添加README说明（如Realtime分支

如果分支无用，希望可以删减以精简项目

**Comment by leelitian** [comment]
master是最新的离线编码器版本，Realtime是实时编码器，cudeptheqt/sobel_qt是增加了快速算法（暂时没有合入master）的版本

**Comment by soaringleefighting** [comment]
@leelitian @Yang-Xijie 请教一下Realtime分支中编译出来的uAVS3和uAVS3_gop什么区别？Realtime模式可以支持Lowdelay P的配置 吗？

**Comment by zywang-sirius** [comment]
AVS3_gop是支持GOP并行的test程序，目前RealTime模式不支持LDP
