### ISSUE TITLE
[编码性能疑问] uavs3-RealTime对比x265性能相差50%左右

### ISSUE THREAD

**Issue by soaringleefighting** [uavs3/uavs3e#37]
如标题，在实测中，Random Access 单线程配置下，uAVS3e-RealTime与x265编码器性能相差很大。采用ClassA~ClassF，另外增加4个额外的4K视频序列，uavs3e-RealTime对比x265编码性能相差50%左右。这个与智媒之音（https://mp.weixin.qq.com/s/cXMHveOYegzuKi2rN7Ftgg）的评测结论相差很大。

**uavs3e采用RealTime分支的最快档次，配置参数如下:**
uAVS3 -f /bin/encoder_ra.cfg -p InputFile= Beauty_3840x2160_50_600.yuv -p OutputFile=Beauty_3840x2160_50_600_Anchor_qp32.bin -p SourceWidth= 3840 -p SourceHeight= 2160 -p FramesToBeEncoded= 600 -p FrameRate=30 -p SpeedLevel=6 -p IntraPeriod=100  -p RateControl=0 -p QP= 32

**x265采用veryfast，具体配置参数如下：**
x265 --input Beauty_3840x2160_50_600.yuv --preset veryfast -t psnr --psnr -o Beauty_3840x2160_50_600_Anchor_qp27.bin --input-res 3840x2160 --fps 30 --keyint 100 --qp 27 --no-wpp -F 1  --bframes 3

**Comment by soaringleefighting** [comment]
@zywang-sirius @luofalei 希望能够回复指导一下，谢谢！

**Comment by soaringleefighting** [comment]
@zywang-sirius @luofalei 在线等。

**Comment by zywang-sirius** [comment]
@soaringleefighting 可以用https://mp.weixin.qq.com/s/cXMHveOYegzuKi2rN7Ftgg中的参数验证一下，如果还是问题，我找我们测试的同学跟你对一下数据

**Comment by soaringleefighting** [comment]
@zywang-sirius 好的，非常感谢！

**Comment by soaringleefighting** [comment]
@zywang-sirius 你好，我这边按照(https://mp.weixin.qq.com/s/cXMHveOYegzuKi2rN7Ftgg)网址的测试条件和配置进行了测试，uAVS3e相比x265，BD-rate平均提升10.5%，耗时增加15倍左右。与智媒之音网址的测试结果也是相差较大。
附：测试数据:
[analysis_result.xlsx](https://github.com/uavs3/uavs3e/files/6899689/analysis_result.xlsx)

**Comment by zywang-sirius** [comment]
加一下微信吧，我找测试的同学跟你对一下

**Comment by zywang-sirius** [comment]
> @zywang-sirius 你好，我这边按照([https://mp.weixin.qq.com/s/cXMHveOYegzuKi2rN7Ftgg)网址的测试条件和配置进行了测试，uAVS3e相比x265，BD-rate平均提升10.5%，耗时增加15倍左右。与智媒之音网址的测试结果也是相差较大。](https://mp.weixin.qq.com/s/cXMHveOYegzuKi2rN7Ftgg)%E7%BD%91%E5%9D%80%E7%9A%84%E6%B5%8B%E8%AF%95%E6%9D%A1%E4%BB%B6%E5%92%8C%E9%85%8D%E7%BD%AE%E8%BF%9B%E8%A1%8C%E4%BA%86%E6%B5%8B%E8%AF%95%EF%BC%8CuAVS3e%E7%9B%B8%E6%AF%94x265%EF%BC%8CBD-rate%E5%B9%B3%E5%9D%87%E6%8F%90%E5%8D%8710.5%%EF%BC%8C%E8%80%97%E6%97%B6%E5%A2%9E%E5%8A%A015%E5%80%8D%E5%B7%A6%E5%8F%B3%E3%80%82%E4%B8%8E%E6%99%BA%E5%AA%92%E4%B9%8B%E9%9F%B3%E7%BD%91%E5%9D%80%E7%9A%84%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C%E4%B9%9F%E6%98%AF%E7%9B%B8%E5%B7%AE%E8%BE%83%E5%A4%A7%E3%80%82)
> 附：测试数据:
> [analysis_result.xlsx](https://github.com/uavs3/uavs3e/files/6899689/analysis_result.xlsx)

加一下微信吧，我找测试的同学跟你对一下

**Comment by soaringleefighting** [comment]
好的，感谢，我的微信号：18105417271

**Comment by soaringleefighting** [comment]
@zywang-sirius 好的，感谢，我的微信号：18105417271
